config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:edit, :update]
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trucks do
    resources :bookings
  end
  get    "my_trucks",      to: "trucks#my_trucks"
  resources :bookings, only: [:index] do
  end
  get 'status_bookings', to: 'bookings#status_bookings'

  patch 'bookings/:id/validate' => 'bookings#validate', as: :validate_booking
  patch 'bookings/:id/refuse' => 'bookings#refuse', as: :refuse_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :truck
  belongs_to :user
  validates :location, :starting_date, :ending_date, presence: true

  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/models/truck.rb
class Truck < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  CATEGORIES = %w(8x4 6x4 4x2 Semi)
  GAUGE = %w(Toupie Grue Benne Bi-Benne)

  validates :gauge, :category, :price, presence: true
  validates :numberplate, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trucks, dependent: :destroy
  has_many :truck_bookings, through: :trucks, :source => :bookings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :avatar_cache])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_truck, only: [ :new, :create, :edit, :update, :destroy, :show ]

  def index
    @bookings = Booking.all

    @bookings = Booking.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@bookings) do |booking, marker|
      marker.lat booking.latitude
      marker.lng booking.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
      end
  end

  def status_bookings
    @pending_bookings_as_owner = current_user.truck_bookings.where(status: "En attente")
    @confirmed_bookings_as_owner = current_user.truck_bookings.where(status: "Confirmé")

    @refused_bookings = current_user.truck_bookings.where(status: "Refusé")
    # @sum_confirmed_price = @confirmed_bookings_as_owner
  end

  def validate
    @booking = Booking.find(params[:id])
    @booking.status = "Confirmé"
    if @booking.save
      redirect_to status_bookings_path
    else
      render 'status_bookings'
    end
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.status = "Refusé"
    if @booking.save
      redirect_to status_bookings_path
    else
      render 'status_bookings'
    end
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.truck = @truck
    @booking.status = "En attente"
    if @booking.save
      redirect_to bookings_path #user_path(current_user)

    else
      render 'new'
    end
  end

  def update
    @booking.update(booking_params)
    redirect_to root_path #user_path(current_user)
  end

  def edit
  end

  def destroy
    @booking.delete
    redirect_to bookings_path
  end

  private

  def set_truck
    @truck = Truck.find(params[:truck_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date, :location, :description, :truck_id, :user_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @trucks = Truck.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(current_user)
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [ :edit, :update, :destroy, :show ]

  def index
    @trucks = Truck.all
    @booking = Booking.new
  end

  def show
  end

  def my_trucks
   @trucks = current_user.trucks
  end

  def new
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)
    @truck.user = current_user
    if @truck.save
      redirect_to my_trucks_path
    else
      render "new"
    end
  end

  def update
    @truck.update(truck_params)
    redirect_to truck_path(@truck)
  end

  def edit
  end

  def destroy
    @truck.delete
    redirect_to my_trucks_path
  end

  private

  def set_truck
    @truck = Truck.find(params[:id])
  end

  def truck_params
    params.require(:truck).permit(:gauge, :category, :description, :availability, :numberplate, :price, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :company, :siret, :address, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/trucks_controller_helper.rb
module TrucksControllerHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@truck, @booking]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :starting_date, as: :string, input_html: { class:"datepicker" } %>
    <%= f.input :ending_date, as: :string, input_html: { class:"datepicker" } %>
    <%= f.input :location %>
    <%= f.input :description %>
  </div>

  <%= content_for(:after_js) do %>
        <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU"></script>

  <% end %>

  <div class="form-actions">
    <%= f.button :submit, hint: "#{link_to 'Book', truck_bookings_path}"%>

  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit your Booking</h1>

<%= render '#/form' %>

app/views/bookings/index.html.erb
<div class="wrapper-dark-blue">
  <div class="text-center">
    <div class="container">
      <div class="row">
        <div class="small-padded">
          <h1>Vos <b>Réservations</b></h1>
        </div>
          <% @bookings.each do |booking| %>
            <% if booking.truck.availability %>
              <div class="col-md-3 col-sm-6">
                <div class="pricingTable">
                  <div class="pricingTable-header">
                    <span class="price-icon"></span>
                    <span class="price-value"><%=booking.truck.price.ceil%>€<span class="month">/jour</span></span>
                    <h3 class="heading"><%= booking.truck.gauge %></h3>
                  </div>
                  <div class="pricingContent">
                    <ul>
                      <li><i class="fa fa-truck"></i><%=booking.truck.category%></li>
                      <li><i class="fa fa-info-circle"></i><%=booking.truck.description%></li>
                      <li><i class="fa fa-map-marker"></i><%=booking.location%></li>
                      <li><i class="fa fa-calendar"></i>Du <%= booking.starting_date.strftime("%d/%m/%Y") %></li>
                      <li><i class="fa fa-calendar"></i>Au <%= booking.ending_date.strftime("%d/%m/%Y") %></li>
                    </ul>
                  </div>
                  <% if booking.status == "En attente" %>
                    <div class="status-pending">
                      <p><%= booking.status  %></p>
                    </div>
                  <% elsif booking.status == "Confirmé"  %>
                    <div class="status-confirmed">
                      <p><i class="fa fa-check style="color:#70C56E></i> <%= booking.status  %></p>
                    </div>
                  <% else %>
                    <div class="status-refused">
                      <p> <i class="fa fa-times style="color:#F60E33></i> <%= booking.status  %></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% else %>
              <h2>Il n'y a pas de camion disponible</h2>
            <% end %>
          <% end %>

        <div class="text-center small-padded">
          <%= link_to t(".top_call_to_action", default: "Réserver d'autres camions"), trucks_path, class: "navbar-wagon-item brand-button btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 padded">
      <div id="map" style="width: 100%; height: 500px; border: 5px solid black">
        <% content_for(:after_js) do %>
          <script>

            // $(document).on('ready', function() {
              console.log("maps");
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
          </script>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New booking</h1>
      <%= render 'form' %>
      <%= link_to 'Back', trucks_path %>
    </div>
  </div>
</div>

app/views/bookings/status_bookings.html.erb
<div class="wrapper-dark-blue bottom-space">
<div class="text-center">
  <div class="container">
      <div class="row">
      <h1>Vos <b>annonces</b></h1>
      <% @pending_bookings_as_owner.each do |booking| %>
            <div class="col-md-3 col-sm-6">
                <div class="pricingTable">
                    <div class="pricingTable-header">
                        <span class="price-icon"></span>
                        <span class="price-value"><%=booking.truck.price.ceil%>€<span class="month">/jour</span></span>
                        <h3 class="heading"><%=  booking.truck.gauge %></h3>
                    </div>
                    <div class="pricingContent">
                        <ul>
                            <li><i class="fa fa-truck"></i><%=booking.truck.category%></li>
                            <li><i class="fa fa-user"></i><%=booking.user.name%></li>
                            <li><i class="fa fa-map" style="color:#F6C667"></i><%= booking.location %>
                            </li>
                            <li><i class="fa fa-calendar"></i>Du <%= booking.starting_date.strftime("%d/%m/%Y") %>
                            </li>
                            <li><i class="fa fa-calendar"></i>Au <%= booking.ending_date.strftime("%d/%m/%Y") %>
                            </li>
                            <% if booking.description.empty? == false %>
                            <li><i class="fa fa-info-circle"></i><%= booking.description %>
                            </li>
                            <li><i class="fa fa-tasks"></i><b><%= booking.status %></b>
                          </li>
                            <% end %>
                        </ul>
                    </div><!-- /  CONTENT BOX-->
                    <div class="pricingTable-signup">
                    <% if booking.status == "En attente" %>
                    <%= link_to 'Valider', validate_booking_path(booking), method: :patch, class: "btn btn-success" %>
                    <%= link_to 'Refuser', refuse_booking_path(booking), method: :patch, class: "btn btn-danger" %>
                    <% end %>
                  </div>
                </div><!-- BUTTON BOX-->
            </div>
          <% end %>
          <% @confirmed_bookings_as_owner.each do |booking| %>
            <div class="col-md-3 col-sm-6">
                <div class="pricingTable">
                    <div class="pricingTable-header">
                        <span class="price-icon"></span>
                        <span class="price-value"><%=booking.truck.price.ceil%>€<span class="month">/jour</span></span>
                        <h3 class="heading"><%=  booking.truck.gauge %></h3>
                    </div>
                    <div class="pricingContent">
                        <ul>
                            <li><i class="fa fa-truck"></i><%=booking.truck.category%></li>
                            <li><i class="fa fa-user"></i><%=booking.user.name%></li>
                            <li><i class="fa fa-map" style="color:#F6C667"></i><%= booking.location %>
                            </li>
                            <li><i class="fa fa-calendar"></i>Du <%= booking.starting_date.strftime("%d/%m/%Y") %>
                            </li>
                            <li><i class="fa fa-calendar"></i>Au <%= booking.ending_date.strftime("%d/%m/%Y") %>
                            </li>
                            <% if booking.description.empty? == false %>
                            <li><i class="fa fa-info-circle"></i><%= booking.description %>
                            </li>
                            <li><i class="fa fa-tasks"></i><b><%= booking.status %></b>
                          </li>
                            <% end %>
                        </ul>
                      </div><!-- /  CONTENT BOX-->
                    <div class="small-padded-alt">
                    <%= link_to 'Refuser', refuse_booking_path(booking), method: :patch, class: "btn btn-danger" %>
                  </div>
                </div><!-- BUTTON BOX-->
              </div>
          <% end %>
          <% @refused_bookings.each do |booking| %>
          <div class="col-md-3 col-sm-6">
              <div class="pricingTable">
                  <div class="pricingTable-header">
                      <span class="price-icon"></span>
                      <span class="price-value"><%=booking.truck.price.ceil%>€<span class="month">/jour</span></span>
                      <h3 class="heading"><%=  booking.truck.gauge %></h3>
                  </div>
                  <div class="pricingContent">
                      <ul>
                          <li><i class="fa fa-truck"></i><%=booking.truck.category%></li>
                          <li><i class="fa fa-user"></i><%=booking.user.name%></li>
                          <li><i class="fa fa-map" style="color:#F6C667"></i><%= booking.location %>
                          </li>
                          <li><i class="fa fa-calendar"></i>Du <%= booking.starting_date.strftime("%d/%m/%Y") %>
                          </li>
                          <li><i class="fa fa-calendar"></i>Au <%= booking.ending_date.strftime("%d/%m/%Y") %>
                          </li>
                          <% if booking.description.empty? == false %>
                          <li><i class="fa fa-info-circle"></i><%= booking.description %>
                          </li>
                          <li><b><i class="fa fa-tasks"></i><%= booking.status %></b>
                          </li>
                          <% end %>
                          </ul>
                      </div><!-- /  CONTENT BOX-->
                    <div class="small-padded-alt">
                    <%= link_to 'Valider', validate_booking_path(booking), method: :patch, class: "btn btn-success" %>
                    </div>
                </div><!-- BUTTON BOX-->
              </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<head>

</head>

<body>
<div class="banner" style="background-image: linear-gradient(-180deg, #071A2E 0%, rgba(24,79,136,0.27) 100%), url(<%= image_url 'banner.jpg' %>);">
  <div class="banner-content text-center">
    <h1><b>Location</b>
     de véhicules de chantier</h1>
     <h1>entre <b>professionnels</b> du BTP</h1>
     <%= link_to t(".top_call_to_action", default: "Louer un camion"), trucks_path, class: "navbar-wagon-item brand-button btn" %>
<!--       <a class="js-scrollTo" href="#scrollTo">
        <div class="mouse">
          <div class="scroll">
          </div>
        </div>
      </a> -->
       <a class="js-scrollTo" href="#scrollTo">
       <div class="mouse-wrap">
         <div class="mouse">
           <div class="frame">
             <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 54.9 91" style="enable-background:new 0 0 54.9 91;" xml:space="preserve">
               <path linejoin="round" stroke-linecap="round" stroke-miterlimit="10" d="M27.4,3.6L27.4,3.6C14.2,3.6,3.5,14.3,3.5,27.5v36c0,13.2,10.7,23.9,23.9,23.9h0c13.2,0,23.9-10.7,23.9-23.9v-36C51.4,14.3,40.7,3.6,27.4,3.6z"></path>
             </svg>
           </div>
           <div class="mouse-left">
             <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 27.4 91" style="enable-background:new 0 0 27.4 91;" xml:space="preserve">
               <path linejoin="round" stroke-linecap="round" stroke-miterlimit="10" d="M27.4,87.5L27.4,87.5c-13.2,0-23.9-10.7-23.9-23.9v-36c0-13.2,10.7-23.9,23.9-23.9h0" class="Animate-Draw"></path>
             </svg>
           </div>
           <div class="mouse-right">
             <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 27.4 91" style="enable-background:new 0 0 27.4 91;" xml:space="preserve">
               <path linejoin="round" stroke-linecap="round" stroke-miterlimit="10" d="M0,3.6L0,3.6c13.2,0,23.9,10.7,23.9,23.9v36c0,13.2-10.7,23.9-23.9,23.9h0" class="Animate-Draw"></path>
             </svg>
           </div>
         </div>
       </div>
      </a>
  </div>
</div>
  <div class="wrapper-dark-home">
    <div class="container">
      <div class="row">
      <div class="small-padded text-center" id="scrollTo">
      <h3>Camions <b>disponibles</b></h3>
      </div>
        <% @trucks.last(4).each do |truck| %>
          <% if truck.availability %>
            <div class="col-md-3 col-sm-6">
                <div class="pricingTable">
                    <div class="pricingTable-header">
                        <span class="price-icon"></span>
                        <span class="price-value"><%=truck.price.ceil%>€<span class="month">/jour</span></span>
                        <h3 class="heading"><%=  truck.gauge %></h3>
                    </div>
                    <div class="pricingContent">
                        <ul>
                            <li><i class="fa fa-truck"></i><%=truck.category%></li>
                            <li><i class="fa fa-info-circle"></i><%=truck.description%></li>
                            <li><i class="fa fa-star" style="color:#F6C667"></i><i class="fa fa-star" style="color:#F6C667"></i><i class="fa fa-star-half-o" style="color:#F6C667"></i>
                            </li>
                        </ul>
                    </div><!-- /  CONTENT BOX-->
                    <div class="pricingTable-signup">
                    <%= link_to t(".top_call_to_action", default: "Louer ce truck"), new_truck_booking_path(truck) %>
                    </div>
                </div><!-- BUTTON BOX-->
            </div>
            <% else %>
              <h2>Il n'y a pas de camion disponible</h2>
            <% end %>
          <% end %>
      </div>
    </div>
<div class="wrapper-yellow">
  <div class="container text-center padded features">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <img src="<%= asset_path('truck.png') %>" alt="">
        <h2>Trouver un camion</h2>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <img src="<%= asset_path('driver.png') %>" alt="">
        <h2>Chauffeur à la demande</h2>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <img src="<%= asset_path('pay.png') %>" alt="">
        <h2>Payez en ligne</h2>
      </div>
    </div>
  </div>
  </div>
  <div class="footer-4cln">
  <div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
              <div class="col-md-3 col-xs-6">
                <h6>L'entreprise</h6>
                  <ul class="list-unstyled">
                    <li><a href="#">A propos</a></li>
                    <li><a href="#">L'équipe</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
              </div>
              <div class="col-md-3 col-xs-6">
                  <h6>Infos</h6>
                  <ul class="list-unstyled">
                    <li><a href="#">Paiement</a></li>
                    <li><a href="#">Légales</a></li>
                    <li><a href="#">Avantages</a></li>
                    <li><a href="#">Support</a></li>
                  </ul>
              </div>
              <div class="col-md-3 col-xs-6">
                  <h6>Aides</h6>
                  <ul class="list-unstyled">
                    <li><a href="#">Réduction</a></li>
                    <li><a href="#">Pourquoi?</a></li>
                    <li><a href="#">Press</a></li>
                    <li><a href="#">Articles</a></li>
                  </ul>
              </div>
              <div class="col-md-3 col-xs-6">
                  <h6>Blague</h6>
                  <ul class="list-unstyled">
                    <li><a href="#">Personne</a></li>
                    <li><a href="#">ne lira</a></li>
                    <li><a href="#">mes</a></li>
                    <li><a href="#">lignes</a></li>
                  </ul>
              </div>
            </div>
          </div>
        <div class="col-md-4">
            <h6>Une question?</h6>
            <form role="form">
              <div class="input-group">
                <input type="email" class="form-control footernews" placeholder="Votre question">
                <span class="input-group-btn">
                    <button class="btn btn-info" type="button">Envoyer</button>
                </span>
              </div>
              <span class="help-block">Réponse très rapide !</span>
            </form>
        </div>
    </div>
    <hr>
      <div class="footer-4cln-bar">
        <span class="phone"><i class="fa fa-phone"></i>01 39 51 69 87</span>
        <span class="email"><i class="fa fa-envelope"></i> <a href="Pedro@camionr.com">pedro@camionr.com</a></span>
        <div class="footer-social">
            <a class="social-facebook" href="#"><i class="fa fa-facebook"></i></a>
            <a class="social-linkedin" href="#"><i class="fa fa-linkedin"></i></a>
            <a class="social-twitter" href="#"><i class="fa fa-twitter"></i></a>
            <a class="social-google" href="#"><i class="fa fa-google-plus"></i></a>
        </div>
        <span class="address">Copyright &copy; Team Pedro<br/> 16 Villa Gaudelet 75011 Paris</span>
      </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $('.js-scrollTo').on('click', function() { // Au clic sur un élément
      var page = $(this).attr('href'); // Page cible
      var speed = 750; // Durée de l'animation (en ms)
      $('html, body').animate( { scrollTop: $(page).offset().top }, speed ); // Go
      return false;
    });
  });
</script>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to t(".top_call_to_action", default: "Ajouter un camion"), new_truck_path, class: "navbar-wagon-item brand-button-border btn" %>
      <%= link_to status_bookings_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-bell"></i>
          <div class="badge badge-yellow">2</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar.url %>
            <%= cl_image_tag current_user.avatar, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "http://placehold.it/32x32", class: "avatar dropdown-toggle", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mes réservations") %>
              <% end %>
            </li>
            <li>
              <%= link_to status_bookings_path do %>
                <i class="fa fa-tag"></i> <%= t(".profile", default: "Mes annonces") %>
              <% end %>
            </li>
            <li>
              <%= link_to my_trucks_path do %>
                <i class="fa fa-truck"></i> <%= t(".profile", default: "Mes Camions") %>
              <% end %>
            </li>
            <li>

              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Deconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <!-- Sign_up -->
      <%= link_to t(".sign_in", default: "Inscription"), new_user_registration_path, class: "navbar-wagon-item brand-button-blue btn" %>

      <!-- Login -->
    <%= link_to t(".top_call_to_action", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item brand-button btn" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mes réservations") %>
              <% end %>
            </li>
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-tag"></i> <%= t(".profile", default: "Mes annonces") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-truck"></i> <%= t(".profile", default: "Mes Camions") %>
              <% end %>
            </li>
            <li>

              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Deconnexion") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>

app/views/trucks/new.html.erb
<div class="wrapper-dark-blue">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h3 class="text-center">Ajouter un nouveau camion</h3>
        <%= render 'form' %>
        <%= link_to 'Back', trucks_path %>
      </div>
    </div>
  </div>
</div>

app/views/trucks/show.html.erb
<div class="wrapper-dark-blue">
<div class="container">
  <div class="row">
     <div class="col-xs-12">
<div class="truck-card text-center">
      <div class="media">
        <div class="media-body">
          <div class="media-section">
            <h2><%= @truck.description %></h2>
          </div>
        </div>
        <div class="media-aside">
          <div class="media-section">
            <h1><%= @truck.category %></h1>
            <h1><%= @truck.gauge %></h1>
          </div>
          <div class="media-section">
            <h2><%= @truck.price %></h2>
          </div>
        </div>
      </div>
       <%= link_to "Retour au resultat de la recherche", trucks_path, class: "button-create-booking btn" %>
      </div>
    </div>
  </div>
</div>
</div>